name: CI
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Test
        run: sbt --client test

      - name: Test publishing
        run: sbt --client publishLocal

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '8'
          cache: 'sbt'

      - name: Publish ${{ github.ref }}
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main'))
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish:
    needs: [build]
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/master'))
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '8'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
